# MeMo HF
Version integrated with Transformer Libraries (Version 0.4)

In [1]:
import torch
from MeMoHF.modelling_memo_tokenizer import MeMoTokenizer
from MeMoHF.modelling_memo_configuration import MeMoConfig
from MeMoHF.modelling_memo import MeMoForCausalLM
from MeMoHF.evaluating_memo import Evaluation

/opt/ubuntu-cuda/anaconda3/envs/EasyEdit/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/opt/ubuntu-cuda/anaconda3/envs/EasyEdit/lib/python3.11/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(


In [2]:
max_length = 12 
tokenizer = MeMoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b", 
                                          truncation_side = 'left',
                                          padding_side='left', max_length=max_length, head_number=4)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPTNeoXTokenizer'. 
The class this function is called from is 'MeMoTokenizer'.


Setting pad token and pad token id = <|endoftext|>, 0


In [3]:
with open("testo_di_prova.txt") as my_first_text_f:
    my_first_text = my_first_text_f.read()

token_ids = tokenizer.encode(my_first_text)#, return_tensors='pt')
print(token_ids) # return max len + 1 

(tensor([[18886,   256, 36144,  4164,  1809,    80,  1448,   295,   532,  1584,
            13, 50190]]), tensor([[  256, 36144,  4164,  1809,    80,  1448,   295,   532,  1584,    13,
         50190,    15]]))


In [4]:
memo_input = tokenizer.get_text_batch_encoding([my_first_text, my_first_text[0:10]])
memo_input.keys(), memo_input['input_ids'].shape

(dict_keys(['input_ids', 'labels']), torch.Size([52, 12]))

In [5]:
for i in range(3):
    print(tokenizer.decode(memo_input['input_ids'][i]))
    print(tokenizer.decode(memo_input['labels'][i]))
    print()

<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>Cosimo di
<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>Cosimo di Giovanni

 de' Medici detto il Vecchio o Pater
' Medici detto il Vecchio o Pater patri

æ (Firenze, 27 settembre 1389
 (Firenze, 27 settembre 1389 –



Check memorization on single layer

In [6]:
memo_input = tokenizer.get_text_batch_encoding([my_first_text, my_first_text[10:30]])

memo_input['input_ids'].shape

torch.Size([52, 12])

In [7]:
from MeMoHF.modelling_memo_embedding import MeMoEmbedding

In [8]:
d,h,l = 1024, 4, 3

In [9]:
embedding = MeMoEmbedding(
    num_embeddings=tokenizer.vocab_size,
    embedding_dim=d,
    padding_idx=tokenizer.pad_token_id, #0
    _freeze=True
)

MeMo embedding initilialization


In [10]:
input_embeddings = embedding.encode(memo_input['input_ids'])
output_symbols = embedding.encode(memo_input['labels'])

input_embeddings.shape, output_symbols.shape

(torch.Size([52, 12, 1024]), torch.Size([52, 12, 1024]))

In [11]:
input_tokens_ids = tokenizer(['Test', 'Un altro Test'])['input_ids']
print(input_tokens_ids)

input_embeddings = embedding.forward(input_tokens_ids)
input_embeddings

tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         5089],
        [   0,    0,    0,    0,    0,    0,    0,    0,    0, 2447, 6945,  287,
         6004]])


tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [-0.0288, -0.0101,  0.0381,  ...,  0.0287,  0.0183, -0.0016]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [-0.0256, -0.0066, -0.0195,  ..., -0.0773,  0.0030,  0.0356],
         [ 0.0496,  0.0230,  0.0170,  ...,  0.0071, -0.0343,  0.0548],
         [ 0.0408, -0.0024,  0.0166,  ..., -0.0026, -0.0240,  0.0150]]])

In [12]:
from MeMoHF.modelling_memo_layer import MeMoLayer

In [13]:
layer = MeMoLayer(d, h)
layer

MeMoLayer(
  (W_v_single_head): ProjectionTokens(in_features=1024, out_features=256)
  (Prj): ProjectionSequence((trasposed wrt saved one) in_features=4096, out_features=1024)
  (CMM): CorrelationMatrixMemory(in_features=1024, out_features=1024)
)

Memo: Initializing the Tokenizer and the model

In [14]:
# Meta Parameters : 
#    d - inner dimension
#    h - number of heads
#    l - number of layers
d,h,l = 1024, 4, 4
chunk_length = 1024

# Initializing a standard Tokenizer
max_length = chunk_length 
tokenizer = MeMoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b", 
                                          padding_side='left', truncation_side='left', 
                                          max_length=max_length, head_number=h)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.pad_token_id

# Intializing Memo Configuration
config = MeMoConfig(vocab_size=tokenizer.vocab_size, 
               hidden_size=d, 
               num_hidden_layers=l,
               num_attention_heads=h,
               chunk_length=chunk_length,
               bos_token_id=tokenizer.bos_token_id,
               eos_token_id=tokenizer.eos_token_id,
               pad_token_id=tokenizer.pad_token_id,
              )

# Initializing the Memo Model from the configuration

model = MeMoForCausalLM(config) 

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)} is available.")
    model.to('cuda')


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPTNeoXTokenizer'. 
The class this function is called from is 'MeMoTokenizer'.


Setting pad token and pad token id = <|endoftext|>, 0
MeMo embedding initilialization
GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU is available.


Reading the two texts

In [15]:
with open("testo_di_prova.txt") as my_first_text_f:
    my_first_text = my_first_text_f.read()
with open("testo_di_prova2.txt") as my_first_text_f:
    my_second_text = my_first_text_f.read()



Memorizing the first text and evaluating if it is memorized

In [16]:
memo_input_1 = tokenizer.get_text_batch_encoding([my_first_text]*8)  # Writing the same doc 8 times to stress the memorization with batch
memo_input_2 = tokenizer.get_text_batch_encoding([my_second_text]*8) # Writing the same doc 8 times to stress the memorization with batch

model.memorize_text(memo_input_1)
e = Evaluation()

e1 = e.check_pretokenized(model, tokenizer, memo_input_1['input_ids'], starting_point=8)
e2 = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'], starting_point=8)

print("Memorization level of first text  : ", e1) 
print("Memorization level of second text : ", e2) 

100%|██████████| 1015/1015 [00:02<00:00, 341.51it/s]

Memorization level of first text  :  tensor(4.4908)
Memorization level of second text :  tensor(0.1725)


Memorizing the second text and checking if it affected the memorization of the first text

In [17]:
model.memorize_text(memo_input_2)

e1 = e.check_pretokenized(model, tokenizer, memo_input_1['input_ids'], starting_point=8)
e2 = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'], starting_point=8)

print("Memorization level of first text  : ", e1) 
print("Memorization level of second text : ", e2) 

100%|██████████| 1015/1015 [00:02<00:00, 339.62it/s]

Memorization level of first text  :  tensor(2.2209)
Memorization level of second text :  tensor(1.2652)


Forgetting the first document

In [18]:
model.forget_text(memo_input_2)

Checking the effect on the two texts

In [19]:
e1 = e.check_pretokenized(model, tokenizer, memo_input_1['input_ids'], starting_point=8)
e2 = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'], starting_point=8)

print("Memorization level of first text  : ", e1) 
print("Memorization level of second text : ", e2) 

100%|██████████| 1015/1015 [00:02<00:00, 338.59it/s]

Memorization level of first text  :  tensor(4.3804)
Memorization level of second text :  tensor(0.1789)


In [20]:
model

MeMoForCausalLM(
  (memo): MeMo(
    (encoder): MeMoEmbedding(50254, 1024, padding_idx=0)
    (layers): MeMoLayers(
      (0-3): 4 x MeMoLayer(
        (W_v_single_head): ProjectionTokens(in_features=1024, out_features=256)
        (Prj): ProjectionSequence((trasposed wrt saved one) in_features=4096, out_features=1024)
        (CMM): CorrelationMatrixMemory(in_features=1024, out_features=1024)
      )
    )
  )
  (lm_head): MeMoEmbedding(50254, 1024, padding_idx=0)
)

In [21]:
with open("testo_di_prova2.txt") as my_first_text_f:
    my_second_text = my_first_text_f.read()


In [22]:
config = MeMoConfig(vocab_size=tokenizer.vocab_size, 
               hidden_size=d, 
               num_hidden_layers=l,
               num_attention_heads=h,
               chunk_length=chunk_length,
               bos_token_id=tokenizer.bos_token_id,
               eos_token_id=tokenizer.eos_token_id,
               pad_token_id=tokenizer.pad_token_id,
              )

# Initializing the Memo Model from the configuration

model = MeMoForCausalLM(config)
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)} is available.")
    model.to('cuda')
print("CMM pre learning")
display(model.memo.layers[0].CMM.weight)


bs = 8
for b in range(bs):
    print(f"memorizing the same text iteration = {b}")
    memo_input = tokenizer.get_text_batch_encoding(my_first_text)
    model.memorize_text(memo_input)

Prj = model.memo.layers[0].Prj.weight.detach().cpu()
CMM = model.memo.layers[0].CMM.weight.detach().cpu()

display(Prj.T @ Prj)
display(CMM)

e = Evaluation()
out = e.check_pretokenized(model, tokenizer, memo_input['input_ids'])
print("Degree of memorization after memorizing 1: %f ", out)


memo_input_2 = tokenizer.get_text_batch_encoding(my_second_text) 
model.memorize_text(memo_input_2)
out = e.check_pretokenized(model, tokenizer, memo_input['input_ids'])
print("Degree of memorization of test 1 after memorizing 2: %f ", out)
out = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'])
print("Degree of memorization of test 2 after memorizing 2: %f ", out)


for b in range(bs):
    print(f"forgetting the same text iteration = {b}")
    memo_input = tokenizer.get_text_batch_encoding(my_first_text)
    model.forget_text(memo_input)

out = e.check_pretokenized(model, tokenizer, memo_input['input_ids'])
print("Degree of memorization of test 1 after forgetting 1: %f ", out)
out = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'])
print("Degree of memorization of test 2 after after forgetting 1: %f ", out)

MeMo embedding initilialization
GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU is available.
CMM pre learning


Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', requires_grad=True)

memorizing the same text iteration = 0
memorizing the same text iteration = 1
memorizing the same text iteration = 2
memorizing the same text iteration = 3
memorizing the same text iteration = 4
memorizing the same text iteration = 5
memorizing the same text iteration = 6
memorizing the same text iteration = 7


tensor([[ 9.9693e-01,  2.5955e-02,  4.7387e-03,  ...,  1.2485e-02,
          1.6907e-04,  5.4028e-03],
        [ 2.5955e-02,  1.0048e+00,  9.2212e-03,  ..., -3.4619e-03,
         -5.3809e-03, -1.1119e-02],
        [ 4.7387e-03,  9.2212e-03,  1.0114e+00,  ...,  3.8127e-02,
         -1.3924e-02, -3.8798e-03],
        ...,
        [ 1.2485e-02, -3.4619e-03,  3.8127e-02,  ...,  1.0081e+00,
          1.4293e-03,  4.0810e-05],
        [ 1.6907e-04, -5.3809e-03, -1.3924e-02,  ...,  1.4293e-03,
          9.9150e-01, -1.2183e-02],
        [ 5.4028e-03, -1.1119e-02, -3.8798e-03,  ...,  4.0810e-05,
         -1.2183e-02,  1.0025e+00]])

tensor([[ 0.0273, -0.0109, -0.0162,  ...,  0.0024,  0.0035, -0.0126],
        [ 0.0083, -0.0162,  0.0155,  ..., -0.0144,  0.0121, -0.0127],
        [-0.0225, -0.0073, -0.0197,  ..., -0.0295, -0.0067,  0.0108],
        ...,
        [-0.0034,  0.0092,  0.0046,  ..., -0.0118, -0.0390,  0.0245],
        [ 0.0094,  0.0057, -0.0008,  ..., -0.0109, -0.0224,  0.0076],
        [ 0.0140,  0.0189,  0.0070,  ...,  0.0190,  0.0161,  0.0194]])

100%|██████████| 767/767 [00:00<00:00, 886.44it/s]


Degree of memorization after memorizing 1: %f  tensor(0.9463)


100%|██████████| 767/767 [00:00<00:00, 897.03it/s]


Degree of memorization of test 1 after memorizing 2: %f  tensor(0.9433)


100%|██████████| 767/767 [00:00<00:00, 860.23it/s]


Degree of memorization of test 2 after memorizing 2: %f  tensor(0.0458)
forgetting the same text iteration = 0
forgetting the same text iteration = 1
forgetting the same text iteration = 2
forgetting the same text iteration = 3
forgetting the same text iteration = 4
forgetting the same text iteration = 5
forgetting the same text iteration = 6
forgetting the same text iteration = 7


100%|██████████| 767/767 [00:00<00:00, 888.14it/s]


Degree of memorization of test 1 after forgetting 1: %f  tensor(0.0399)


100%|██████████| 767/767 [00:00<00:00, 867.70it/s]

Degree of memorization of test 2 after after forgetting 1: %f  tensor(0.8506)


In [23]:
# code for testing generation capabilities of MeMo
model.eval()

memo_input_test = tokenizer.get_text_batch_encoding(my_first_text)
print(f'text={my_first_text}\nmemo_input={memo_input_test}')

generated_text = model.generate(inputs=memo_input_test['input_ids'], max_new_tokens=3)

generated_text.shape
final_text = tokenizer.decode(generated_text[0], skip_special_token=True)
print(final_text)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


text=Cosimo di Giovanni de' Medici detto il Vecchio o Pater patriæ (Firenze, 27 settembre 1389 – Careggi, 1º agosto 1464) è stato un politico e banchiere italiano, primo signore de facto di Firenze e primo uomo di Stato di rilievo della famiglia Medici. Pur non avendo mai ricoperto alcuna carica di rilievo nella città (che si mantenne sempre istituzionalmente una Repubblica), egli si poté considerare il massimo uomo di Firenze all'indomani della morte del padre Giovanni (dal quale raccolse l'eredità economica), e in particolare con il ritorno glorioso dall'esilio nel 1434.
Grazie alla sua politica moderata, egli riuscì a conservare il potere per oltre trent'anni fino alla morte, gestendo lo Stato in modo silenzioso attraverso suoi uomini di fiducia e permettendo, in questo modo, il consolidamento della sua famiglia al governo di Firenze. Abile diplomatico, riuscì a capovolgere le alleanze politiche italiane all'indomani della morte di Filippo Maria Visconti, facendo alleare Firenze con

/opt/anaconda3/envs/EasyEdit/lib/python3.10/site-packages/transformers/generation/utils.py:2136: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(


In [24]:
tokenizer.tokenize(my_first_text)

['Cos',
 'imo',
 'Ġdi',
 'ĠGiovanni',
 'Ġde',
 "'",
 'ĠMedic',
 'i',
 'Ġdet',
 'to',
 'Ġil',
 'ĠVec',
 'chio',
 'Ġo',
 'ĠP',
 'ater',
 'Ġpatri',
 'æ',
 'Ġ(',
 'Fi',
 'ren',
 'ze',
 ',',
 'Ġ27',
 'Ġsett',
 'em',
 'bre',
 'Ġ138',
 '9',
 'ĠâĢĵ',
 'ĠCare',
 'gg',
 'i',
 ',',
 'Ġ1',
 'º',
 'Ġag',
 'osto',
 'Ġ14',
 '64',
 ')',
 'Ġè',
 'Ġstato',
 'Ġun',
 'Ġpolit',
 'ico',
 'Ġe',
 'Ġban',
 'chie',
 're',
 'Ġit',
 'alian',
 'o',
 ',',
 'Ġprim',
 'o',
 'Ġsign',
 'ore',
 'Ġde',
 'Ġfacto',
 'Ġdi',
 'ĠFi',
 'ren',
 'ze',
 'Ġe',
 'Ġprim',
 'o',
 'Ġu',
 'omo',
 'Ġdi',
 'ĠSt',
 'ato',
 'Ġdi',
 'Ġr',
 'il',
 'ie',
 'vo',
 'Ġdella',
 'Ġfam',
 'ig',
 'lia',
 'ĠMedic',
 'i',
 '.',
 'ĠPur',
 'Ġnon',
 'Ġav',
 'endo',
 'Ġmai',
 'Ġric',
 'op',
 'erto',
 'Ġalc',
 'una',
 'Ġcar',
 'ica',
 'Ġdi',
 'Ġr',
 'il',
 'ie',
 'vo',
 'Ġnella',
 'Ġc',
 'itt',
 'Ãł',
 'Ġ(',
 'che',
 'Ġsi',
 'Ġmant',
 'enne',
 'Ġsempre',
 'Ġist',
 'it',
 'uz',
 'ional',
 'mente',
 'Ġuna',
 'ĠRep',
 'ub',
 'blic',
 'a',
 '),',
 'Ġeg',
 'l