# MeMo Torch 
Version integrated with Torch (Keras)

In [1]:
import torch
from MeMoPyTorch.modelling_memo import MeMo
from MeMoPyTorch.modelling_memo_tokenizer import MeMoTokenizer
from MeMoPyTorch.evaluating_memo import Evaluation

Memo: Initializing the Tokenizer and the model

In [2]:
# Meta Parameters : 
#    d - inner dimension
#    h - number of heads
#    l - number of layers
d,h,l = 2048, 4, 2
chunk_length = h**(l+1)

# Initializing a standard Tokenizer
max_length = chunk_length 
tokenizer = MeMoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b", 
                                          padding_side='left', truncation_side='left', 
                                          max_length=max_length, head_number=h)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.pad_token_id
del tokenizer.added_tokens_encoder['                        ']
del tokenizer.added_tokens_decoder[50254]

device = 'cpu'
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)} is available.")
    device = 'cuda'

# Intializing Memo 
model = MeMo(inner_dim=d, 
             num_of_heads=h, 
             num_of_layers=l, 
             chunk_length=max_length, 
             num_embeddings=tokenizer.vocab_size+1, 
             padding_idx=tokenizer.pad_token_id,
             padding_seq_idx=tokenizer.vocab_size,  
             device=device)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPTNeoXTokenizer'. 
The class this function is called from is 'MeMoTokenizer'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Setting pad token and pad token id = <|endoftext|>, 0
MeMo embedding initilialization


In [3]:
with open("testo_di_prova.txt") as my_first_text_f:
    my_first_text = my_first_text_f.read()


memo_input_1 = tokenizer.get_text_batch_encoding([my_first_text, my_first_text[0:10]])
memo_input_1.keys(), memo_input_1['input_ids'].shape
memo_input_1 = tokenizer.get_text_batch_encoding([my_first_text]*8)
memo_input_1['input_ids'][1]


tensor([ 3414,   358,  3381, 15410,    26, 25404, 14507,  1628,  9776,  1266,
           74,    13,   337,  7974, 11703,   639, 39337,  1638,  1540,    10,
        24449, 20335, 48019,   440,  2314,  4173,   299,  8913,  2942,   250,
          352,  6770,    80,    13,  2248,    80,   861,   410,   372, 32924,
         1073, 33813,   445,  2721,   299,  2248,    80,  1484, 19216,  1073,
          659,  4611,  1073,   391,   300,   466,  5711, 14804,  1431,   304,
        19702,  9718,    74,    15])

In [4]:
with open("testo_di_prova2.txt") as my_first_text_f:
    my_second_text = my_first_text_f.read()

Memorizing the first text and evaluating if it is memorized

In [5]:
memo_input_1 = tokenizer.get_text_batch_encoding([my_first_text]*1)  # Writing the same doc 8 times to stress the memorization with batch
memo_input_2 = tokenizer.get_text_batch_encoding([my_second_text]*1) # Writing the same doc 8 times to stress the memorization with batch

model.memorize_text(memo_input_1)
e = Evaluation()

e1 = e.check_pretokenized(model, tokenizer, memo_input_1['input_ids'], starting_point=8)
e2 = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'], starting_point=8)

print("Memorization level of first text  : ", e1) 
print("Memorization level of second text : ", e2) 

Starting point : 8


100%|██████████| 55/55 [00:03<00:00, 15.29it/s]


Starting point : 8


100%|██████████| 55/55 [00:07<00:00,  7.25it/s]

Memorization level of first text  :  tensor(0.9948)
Memorization level of second text :  tensor(0.0306)


In [5]:
pred, score = model.retrieve(memo_input_1['input_ids'])
pred == memo_input_1['labels'][..., -1]

tensor([ True,  True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True])

In [6]:
pred, score = model.retrieve(memo_input_1['input_ids'][:, :32])
pred ==  memo_input_1['input_ids'][:, 32]

tensor([True, True, True, True, True, True, True, True, True, True, True])

In [7]:
pred, score = model.retrieve(memo_input_1['input_ids'][:, :10])
pred ==  memo_input_1['input_ids'][:, 10]

tensor([True, True, True, True, True, True, True, True, True, True, True])

In [8]:
model.forget_text(memo_input_1)

In [8]:
pred, score = model.retrieve(memo_input_1['input_ids'])
pred == memo_input_1['labels'][..., -1]

tensor([ True,  True,  True,  True,  True,  True,  True,  True, False,  True,
         True])

In [9]:
model.memorize_text(memo_input_2)

In [10]:
e1 = e.check_pretokenized(model, tokenizer, memo_input_1['input_ids'], starting_point=0)
e2 = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'], starting_point=0)

print("Memorization level of first text  : ", e1) 
print("Memorization level of second text : ", e2) 

Starting point : 0


100%|██████████| 63/63 [00:04<00:00, 14.49it/s]


Starting point : 0


100%|██████████| 63/63 [00:07<00:00,  8.30it/s]

Memorization level of first text  :  tensor(0.9510)
Memorization level of second text :  tensor(0.9489)


In [11]:
model.forget_text(memo_input_2)

In [12]:
e1 = e.check_pretokenized(model, tokenizer, memo_input_1['input_ids'], starting_point=8)
e2 = e.check_pretokenized(model, tokenizer, memo_input_2['input_ids'], starting_point=8)

print("Memorization level of first text  : ", e1) 
print("Memorization level of second text : ", e2) 

Starting point : 8


100%|██████████| 55/55 [00:03<00:00, 14.06it/s]


Starting point : 8


100%|██████████| 55/55 [00:07<00:00,  7.73it/s]

Memorization level of first text  :  tensor(0.9948)
Memorization level of second text :  tensor(0.0306)


In [10]:
# ########### DEBUGGING CODE ############


import numpy as np

def generate_sequences_original(input_seqs, h:int, layer:int):
    PAD = -1

    indexes = list(range(input_seqs.shape[1]))
    whento = np.array([([PAD]*(i*(h ** layer)) + indexes)[:len(indexes)] for i in range(h)][::-1]).T.tolist()
    print("whento", whento)

    new_seqs = []
    for selected in whento:
        #print("selected", selected)
        new_seq = [model.encoder.weight[model.encoder.padding_seq_idx].expand(input_seqs.shape[0], -1) if x == PAD 
                   else input_seqs[:, x] for x in selected]

        #print("New sequence:")
        #for i in range(len(new_seq)): ### evidence that the selected sequence is correct
        #    print(selected[i])
        #    print(new_seq[i])
            
        
        new_seq = torch.stack(new_seq, axis=1)
        #print(model.encoder.decode(new_seq)) ### evidence that the padding with ones breaks the decoding
        # print("new_seq.shape", new_seq.shape)
        # print()
        new_seqs.append(new_seq)
    
    return torch.stack(new_seqs, axis=1)


def generate_sequences(input_seqs, h: int, layer: int):

    batch_size, seq_len, hidden_dim = input_seqs.shape
    device = input_seqs.device

    # Distance between selected positions
    step = h ** layer

    # Construct:
    #
    # layer=0, h=4
    #
    # [-1, -1, -1,  0]
    # [-1, -1,  0,  1]
    # [-1,  0,  1,  2]
    # [ 0,  1,  2,  3]
    # ...
    positions = torch.arange(seq_len, device=device)

    offsets = (
        torch.arange(h, device=device) - (h - 1)
    ) * step

    whento = positions[:, None] + offsets[None, :]

    # Everything before the sequence becomes PAD = -1
    whento = whento.clamp(min=-1)
    print("whento", whento)

    # Keep track of padding positions
    valid = whento != -1

    # Replace -1 with 0 temporarily for indexing
    gather_indices = whento.clamp(min=0)

    # [batch, seq_len, h, hidden_dim]
    new_seqs = input_seqs[:, gather_indices]

    # Padding embedding
    padding = model.encoder.weight[
        model.encoder.padding_seq_idx
    ].view(1, 1, 1, hidden_dim)

    # Replace invalid gathered values with padding
    new_seqs = torch.where(
        valid[None, :, :, None],
        new_seqs,
        padding
    )

    return new_seqs

def process_input_seq(input_seq):
    input_seq = input_seq[:, : , -1]
    return input_seq

DEBUG = True
if DEBUG: 
    h = 4
    PAD = "PAD"
    layers = 3
    sequence_length = 65
    print(f"{'='*30} sequence size: {sequence_length-1} {'='*30}")
    print(f"{'='*30} total layers: {layers+1} {'='*30}\n\n")

    # input_ids = {
    #     "input_ids": torch.tensor([list(range(1, 66)), list(range(1, 66))])
    # }
    # memo_input_1 = tokenizer.get_memo_input(input_ids)

    # memo_input_1

    memo_input_1 = torch.tensor([list(range(sequence_length, 2*sequence_length)), list(range(sequence_length, 2*sequence_length))])
    memo_input_1 = {"input_ids": memo_input_1, "labels": memo_input_1}


    input_seq = model.encoder.encode(memo_input_1['input_ids'])

    for l in range(layers):
        print(f"{'='*90} LAYER {l}:\n")
        input_seq = generate_sequences(input_seqs=input_seq, h=h, layer=l)
        print("Input sequence at this layer:")
        print(model.encoder.decode(input_seq)[0])
        print("input_seq.shape", input_seq.shape)
        input_seq = process_input_seq(input_seq=input_seq)
        print("Input sequence after processing:")
        print(model.encoder.decode(input_seq)[0])
        print("processed_input_seq.shape", input_seq.shape)

# ########### DEBUGGING CODE ############


============================== sequence size: 64 ==============================
============================== total layers: 4 ==============================


========================================================================================== LAYER 0:

whento tensor([[-1, -1, -1,  0],
        [-1, -1,  0,  1],
        [-1,  0,  1,  2],
        [ 0,  1,  2,  3],
        [ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6],
        [ 4,  5,  6,  7],
        [ 5,  6,  7,  8],
        [ 6,  7,  8,  9],
        [ 7,  8,  9, 10],
        [ 8,  9, 10, 11],
        [ 9, 10, 11, 12],
        [10, 11, 12, 13],
        [11, 12, 13, 14],
        [12, 13, 14, 15],
        [13, 14, 15, 16],
        [14, 15, 16, 17],
        [15, 16, 17, 18],
        [16, 17, 18, 19],
        [17, 18, 19, 20],
        [18, 19, 20, 21],
        [19, 20, 21, 22],
        [20, 21, 22, 23],
        [21, 22, 23, 24],
        [22, 23, 24, 25],
        [23, 24, 25, 26],
        [24, 25, 26, 27],
    

In [11]:
memo_input_1['input_ids'].shape

torch.Size([2, 65])

In [12]:
########### DEBUGGING CODE for INTEGRITY of the DECODING STEP############
if DEBUG:
    input_seq = memo_input_1['input_ids']
    input_seq = model.encoder.encode(input_seq)

    input_seq = generate_sequences(input_seqs=input_seq, h=h, layer=0)
    for i in input_seq:
        print("Decoded sequence:")
        dec = model.encoder.decode(i)
        print("pred", dec[0])
        print("values", dec[1])

whento tensor([[-1, -1, -1,  0],
        [-1, -1,  0,  1],
        [-1,  0,  1,  2],
        [ 0,  1,  2,  3],
        [ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6],
        [ 4,  5,  6,  7],
        [ 5,  6,  7,  8],
        [ 6,  7,  8,  9],
        [ 7,  8,  9, 10],
        [ 8,  9, 10, 11],
        [ 9, 10, 11, 12],
        [10, 11, 12, 13],
        [11, 12, 13, 14],
        [12, 13, 14, 15],
        [13, 14, 15, 16],
        [14, 15, 16, 17],
        [15, 16, 17, 18],
        [16, 17, 18, 19],
        [17, 18, 19, 20],
        [18, 19, 20, 21],
        [19, 20, 21, 22],
        [20, 21, 22, 23],
        [21, 22, 23, 24],
        [22, 23, 24, 25],
        [23, 24, 25, 26],
        [24, 25, 26, 27],
        [25, 26, 27, 28],
        [26, 27, 28, 29],
        [27, 28, 29, 30],
        [28, 29, 30, 31],
        [29, 30, 31, 32],
        [30, 31, 32, 33],
        [31, 32, 33, 34],
        [32, 33, 34, 35],
        [33, 34, 35, 36],
        [34, 35, 36, 37],
     